### ISSUE TITLE
Setup Unit and Integration tests

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/ngrok-ingress-controller#39]
While we have our e2e suite to test overall functionality, we should also setup lower level tests. 
* Plain go unit tests where they provide value
* Kubebuilder tests frameworks
  * https://betterprogramming.pub/write-tests-for-your-kubernetes-operator-d3d6a9530840
  * https://book.kubebuilder.io/reference/envtest.html?highlight=envtest#configuring-envtest-for-integration-tests
 * Other test frameworks like k6s or Ginkgo for integration style tests

**Comment by jonstacks** [comment]
Closing this as resolved for now since we have unit tests and the e2e tests. Will re-open when we decide we need kubebuilder or ginko style tests.
