### ISSUE TITLE
Publish Multiple docker build architectures 

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/ngrok-ingress-controller#59]

**Comment by alex-bezek** [comment]
@mschenck You have more context on what other architectures would be useful to build, would you mind filling out this issue with the more immediate and the long term architectures we should target?

**Comment by jonstacks** [comment]
I think this will be fairly straightforward using `buildx` from Docker's [multi-platform guide](https://docs.docker.com/build/building/multi-platform/). Seems like its fairly easy to add a new arch in though. I think initially we want to support at least `amd64` and `arm64`.
