### ISSUE TITLE
Make a little magic happen

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/ngrok-ingress-controller#63]
as a part of the notes.txt that runs after the helm installation, we should output some useful information about next steps the user could take to see some useful functionality of ngrok very quickly. This is open to other ideas but the one that was brought up was to query the cluster for the k8s dashboard and if present output an example of the ingress object needed to expose it behind oauth

**Comment by alex-bezek** [comment]
Another option would be to look for services on port 80 and 443 as good potential options to output an example for. Or even a generic example

**Comment by mschenck** [comment]
I'm happy to close this ticket for now, but I'm leaving it open while looking for some additional ideas for _magic_.

**Comment by mschenck** [comment]
closing for now.  More enhancements down the road
